---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux-helm-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flux-helm-operator
    spec:
      serviceAccount: flux
      volumes:
      # The following volume is for using customised known_hosts file,
      # which you will need to do if you host your own git repo rather
      # than using github or the like. You'll also need to mount it
      # into the container, below.
      # You may also wish to provide an ssh_config file as well,
      # mentioning more than one Identity; for instance, if you're
      # using more than one GitHub repo. NB the entry key should be
      # "config" if mounted in ~/.ssh/.
      # - name: sshdir
      #   configMap:
      #     name: flux-ssh-config
      #     defaultMode: 0400
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400 # when mounted read-only, we won't be able to chmod
      containers:
      - name: flux-helm-operator
        # There are no ":latest" images for helm-operator. Find the most recent
        # release or image version at https://quay.io/weaveworks/helm-operator
        # and replace the tag here.
        image: quay.io/weaveworks/helm-operator:0.2.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        # Include this if you need to mount a customised known_hosts or ssh_config
        # file; you'll also need the volume declared above.
        # - name: sshdir
        #   mountPath: /root/.ssh
        #   readOnly: true
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true # this will be the case perforce in K8s >=1.10
